controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
  - name: fake_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home

  []